export const PROJECTS = [
  {
    id: "billbuster",
    title: "BillBuster",
    subtitle: "Intelligent Expense Splitting · FinTech iOS App",
    desc: "Scalable iOS app for group financial management. Automated bill calculation logic eliminates manual reconciliation errors. Analytics-ready data structures with CoreData persistence.",
    tags: ["Swift", "SwiftUI", "CoreData", "FinTech"],
    link: "https://github.com/krishaygahlaut/BillBuster",
    date: "Jun 2025",
    scene: "phone",
    accentColor: "#4DFFD2",
    bullets: [
      "Scalable expense-splitting for group financial management",
      "Automated bill calculation to eliminate reconciliation errors",
      "Persistent local storage using CoreData",
      "Analytics-ready data structures for expense insights",
    ],
  },
  {
    id: "chess",
    title: "AI Chess Engine",
    subtitle: "Minimax Algorithm · Artificial Intelligence",
    desc: "Rule-based chess engine using OOP principles and the Minimax algorithm for intelligent move prediction. Full game state management with check detection and optimized recursive evaluation.",
    tags: ["Python", "OOP", "Minimax", "AI"],
    link: "#",
    date: "Jul 2026",
    scene: "neural",
    accentColor: "#7B61FF",
    bullets: [
      "Rule-based engine using object-oriented programming",
      "Minimax algorithm for intelligent move prediction",
      "Validation logic for legal moves and check detection",
      "Optimized recursive evaluation functions",
    ],
  },
  {
    id: "robot",
    title: "Line Following Robot",
    subtitle: "Arduino · Embedded Systems · Robotics",
    desc: "Four-wheel autonomous robot with real-time IR-based line tracking. L298N motor driver interfacing with dynamic speed adjustment for precise path correction and stability.",
    tags: ["Arduino UNO", "Embedded C", "IR Sensors", "L298N"],
    link: "#",
    date: "Oct–Nov 2025",
    scene: "robot",
    accentColor: "#00979D",
    bullets: [
      "Four-wheel autonomous robot with real-time line tracking",
      "IR sensors to detect contrast between surfaces",
      "Embedded control logic for dynamic motor speed adjustment",
      "Motor driver (L298N) interfacing for directional control",
    ],
  },
  {
    id: "fitfuel",
    title: "FitFuel",
    subtitle: "Smart Meal Logger & Calorie Tracker · iOS",
    desc: "Privacy-first iOS app with MVVM architecture for meal logging, calorie tracking, and nutritional analysis. Fully offline, blazing fast, with PhotosUI and HealthKit integration.",
    tags: ["SwiftUI", "MVVM", "PhotosUI", "HealthKit"],
    link: "https://github.com/krishaygahlaut/FitFuel",
    date: "Apr–Jun 2025",
    scene: "phone",
    accentColor: "#FF6B35",
    bullets: [
      "MVVM architecture for clean separation of concerns",
      "PhotosUI integration for meal photo logging",
      "HealthKit sync for nutritional data",
      "Fully offline, privacy-first design",
    ],
  },
  {
    id: "weatherly",
    title: "Weatherly",
    subtitle: "Real-Time Weather Forecasting · iOS App",
    desc: "Production-grade iOS weather app with CoreLocation geolocation, REST API integration, and smooth MVVM state management with animated UI and responsive design.",
    tags: ["Swift", "SwiftUI", "CoreLocation", "REST API"],
    link: "https://github.com/krishaygahlaut/Weatherly",
    date: "May–Jun 2025",
    scene: "phone",
    accentColor: "#4DFFD2",
    bullets: [
      "Real-time weather forecasting via REST APIs",
      "CoreLocation for accurate geolocation-based updates",
      "Responsive, production-ready UI with smooth animations",
      "Clean MVVM architecture with scalable code practices",
    ],
  },
];

export const CERTIFICATIONS = [
  // Tier 1 — Industry/Professional
  {
    name: "AWS Certified AI Practitioner",
    org: "Amazon Web Services",
    date: "Mar 2026",
    expiry: "Mar 2029",
    id: "0b8bc17276764f3db5742f5f94452a4a",
    verifyUrl: "https://aws.amazon.com/verification",
    color: "#FF9900",
    tier: "professional",
    icon: "☁️",
  },
  {
    name: "AWS Certified Cloud Practitioner",
    org: "Amazon Web Services",
    date: "Mar 2026",
    expiry: "Mar 2029",
    id: "d7cec4b07a4642ed87ab566a2cac16e3",
    verifyUrl: "https://aws.amazon.com/verification",
    color: "#FF9900",
    tier: "professional",
    icon: "☁️",
  },
  {
    name: "Networking Basics",
    org: "Cisco Networking Academy",
    date: "Oct 2025",
    id: "",
    verifyUrl: "#",
    color: "#00BCEB",
    tier: "professional",
    icon: "🌐",
  },
  // Tier 2 — Udemy
  {
    name: "iOS & Swift — Complete iOS Dev Bootcamp",
    org: "Udemy · Dr. Angela Yu",
    date: "Sep 2025",
    id: "UC-ce3dc6aa-28a4-424f-a984-35a71514fc73",
    verifyUrl: "https://ude.my/UC-ce3dc6aa-28a4-424f-a984-35a71514fc73",
    color: "#A435F0",
    tier: "course",
    icon: "📱",
    hours: "60.5 hrs",
  },
  {
    name: "Mastering DSA — C and C++",
    org: "Udemy · Abdul Bari",
    date: "Sep 2025",
    id: "UC-6bc28171-341d-4d22-81e2-1b9320d8d3b9",
    verifyUrl: "https://ude.my/UC-6bc28171-341d-4d22-81e2-1b9320d8d3b9",
    color: "#A435F0",
    tier: "course",
    icon: "🧮",
    hours: "76 hrs",
  },
  {
    name: "Mastering Machine Learning",
    org: "Udemy · Anitha K & Dr. R. Anto",
    date: "Sep 2025",
    id: "UC-fb83c280-303a-4902-a1e7-5325cd4dffb9",
    verifyUrl: "https://ude.my/UC-fb83c280-303a-4902-a1e7-5325cd4dffb9",
    color: "#A435F0",
    tier: "course",
    icon: "🤖",
    hours: "6 hrs",
  },
  {
    name: "Full-Stack Web Dev Bootcamp",
    org: "Udemy · Dr. Angela Yu",
    date: "Sep 2025",
    id: "UC-6616bad3-d1cd-436b-b907-fe382976090e",
    verifyUrl: "https://ude.my/UC-6616bad3-d1cd-436b-b907-fe382976090e",
    color: "#A435F0",
    tier: "course",
    icon: "🌐",
    hours: "61.5 hrs",
  },
  // Tier 3 — NPTEL
  {
    name: "Programming in Java",
    org: "NPTEL · IIT Kharagpur",
    date: "Oct 2024",
    id: "NPTEL24CS105S152504236",
    verifyUrl: "#",
    color: "#4DFFD2",
    tier: "academic",
    icon: "☕",
    score: "57%",
  },
  // Tier 4 — MathWorks
  {
    name: "Machine Learning Onramp",
    org: "MathWorks MATLAB",
    date: "Apr 2025",
    id: "",
    verifyUrl: "#",
    color: "#E16F24",
    tier: "academic",
    icon: "🔬",
  },
  {
    name: "Deep Learning Onramp",
    org: "MathWorks MATLAB",
    date: "Apr 2025",
    id: "",
    verifyUrl: "#",
    color: "#E16F24",
    tier: "academic",
    icon: "🧠",
  },
  {
    name: "Image Processing Onramp",
    org: "MathWorks MATLAB",
    date: "Mar 2025",
    id: "",
    verifyUrl: "#",
    color: "#E16F24",
    tier: "academic",
    icon: "🖼️",
  },
  {
    name: "MATLAB Onramp",
    org: "MathWorks MATLAB",
    date: "Mar 2025",
    id: "",
    verifyUrl: "#",
    color: "#E16F24",
    tier: "academic",
    icon: "📊",
  },
];

export const SKILLS = [
  {
    category: "Languages",
    color: "#4DFFD2",
    items: ["Swift", "Python", "Java", "C", "C++", "MATLAB"],
  },
  {
    category: "iOS / Apple",
    color: "#FF6B35",
    items: ["SwiftUI", "CoreData", "CoreLocation", "HealthKit", "PhotosUI", "MVVM", "Xcode"],
  },
  {
    category: "AI / ML",
    color: "#7B61FF",
    items: ["Machine Learning", "Deep Learning", "Image Processing", "Minimax / Game AI", "OOP", "DSA"],
  },
  {
    category: "Web & Cloud",
    color: "#FFD93D",
    items: ["React", "Next.js", "Node.js", "REST APIs", "AWS Cloud", "Full-Stack Dev"],
  },
  {
    category: "Embedded & Systems",
    color: "#00979D",
    items: ["Arduino", "Embedded C", "IR Sensors", "Motor Driver (L298N)", "Robotics", "Networking"],
  },
  {
    category: "Tools",
    color: "#FF9900",
    items: ["Git & GitHub", "Xcode", "Arduino IDE", "MATLAB", "Vercel", "Firebase"],
  },
];

export const EDUCATION = [
  {
    school: "SRM Institute of Science and Technology",
    degree: "B.Tech · Computer Science and Engineering",
    year: "2023–2027",
    grade: "CGPA: 8.28 / 10",
    location: "Kattankulathur, Tamil Nadu",
    color: "#4DFFD2",
  },
  {
    school: "P.M.S Public School",
    degree: "Class XII · CBSE",
    year: "2023",
    grade: "72.6%",
    location: "Moradabad, Uttar Pradesh",
    color: "#7B61FF",
  },
  {
    school: "Maria School",
    degree: "Class X · ICSE",
    year: "2021",
    grade: "80%",
    location: "Uttarakhand",
    color: "#FF6B35",
  },
];

export const VOLUNTEERING = {
  org: "Indian Red Cross Society",
  role: "Event Volunteer & Camp Coordinator",
  desc: "Volunteered at a 24-hour Blood Donation Camp with the Indian Red Cross Society — District Branch, Jaspur, Uttarakhand. Supported donor coordination and on-ground operations, contributing to 100+ units collected.",
  coverage: "Jaspur Times — 24-Hour Blood Donation Camp Coverage",
  link: "https://jaspurtimes.com/3927/",
};
